### ISSUE TITLE
Uncaught SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by TheFinality** [hostedposted/Prodigy#1]
Throws error of Uncaught SyntaxError: Unexpected token . at 70:70. I am working on the dashboard, but this error throws, and i cannot login. I can't fix it, help please.

**Comment by ashtoncoded** [comment]
Can you provide a certain function which this occurs in.

**Comment by TheFinality** [comment]
yes, it is in the gett player gold

**Comment by hostedposted** [comment]
This is because your browser does not support optional chaining. The only thing we can do is use babel which I am not going to use.
